

CREATE TABLE TRFT_CLIENT  (
   CD_CLIENT            NUMBER(10)                       NOT NULL,
   RAISON_SOCIAL        VARCHAR2(20),
   ADRESSE_POSTALE      VARCHAR2(100),
   CODE_POSTAL          VARCHAR2(8),
   VILLE                VARCHAR2(20),
   PAYS                 VARCHAR2(20),
   CONSTRAINT PK_TRFT_CLIENT PRIMARY KEY (CD_CLIENT)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_CLIENT_SERVEUR  (
   CD_CLIENT            NUMBER(10)                       NOT NULL,
   CD_SRV               NUMBER(10)                       NOT NULL,
   CONSTRAINT PK_TRFT_CLIENT_SERVEUR PRIMARY KEY (CD_CLIENT, CD_SRV)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_FLUX  (
   CD_FLUX              NUMBER(10)                       NOT NULL,
   DESIGNATION          VARCHAR2(100),
   CONSTRAINT PK_TRFT_FLUX PRIMARY KEY (CD_FLUX)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_SERVEURS  (
   CD_SRV               NUMBER(10)                       NOT NULL,
   CD_CLIENT_SRV        NUMBER(10)                       NOT NULL,
   ADRESSE_IP           VARCHAR2(20)                     NOT NULL,
   FTP_IDENTIFIANT      VARCHAR2(20)                     NOT NULL,
   FTP_MDP              VARCHAR2(20)                     NOT NULL,
   FTP_PORT             NUMBER(6)                        NOT NULL,
   TRFT_PORT            NUMBER(6)                        NOT NULL,
   CONSTRAINT PK_TRFT_SERVEURS PRIMARY KEY (CD_SRV)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_SERVEUR_FLUX  (
   CD_FLUX              NUMBER(10)                       NOT NULL,
   CD_SRV               NUMBER(10)                       NOT NULL,
   CHEMIN_LOCAL         VARCHAR2(100),
   CHEMIN_DISTANT       VARCHAR2(100),
   CONSTRAINT PK_TRFT_SERVEUR_FLUX PRIMARY KEY (CD_FLUX, CD_SRV)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_TRANSACTION  (
   CD_TRST              NUMBER(30)                      NOT NULL,
   CD_TRFT              NUMBER(30)                       NOT NULL,
   DETAIL               VARCHAR2(100),
   CODE_ERREUR          VARCHAR2(100),
   ETAT                 VARCHAR2(20),
   DATE_TRANSACTION     DATE,
   CONSTRAINT PK_TRFT_TRANSACTION PRIMARY KEY (CD_TRST)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/




CREATE TABLE TRFT_TRANSFERT  (
   CD_TRFT              NUMBER(30)                       NOT NULL,
   CD_FLUX              NUMBER(10)                       NOT NULL,
   CD_CLIENT            NUMBER(10),
   DESIGNATION          VARCHAR2(100),
   TAILLE_FICHIER       VARCHAR2(100),
   ETAT                 VARCHAR2(20),
   IP_SOURCE            VARCHAR2(20),
   DATE_TRANSFERT       DATE,
   CONSTRAINT PK_TRFT_TRANSFERT PRIMARY KEY (CD_TRFT)
         USING INDEX
       TABLESPACE EXT_IDX
)
TABLESPACE EXT_TBS
/


ALTER TABLE TRFT_CLIENT_SERVEUR
   ADD CONSTRAINT FK_TRFT_CLI_TRFT_CLIE_TRFT_CLI FOREIGN KEY (CD_CLIENT)
      REFERENCES TRFT_CLIENT (CD_CLIENT)
/


ALTER TABLE TRFT_CLIENT_SERVEUR
   ADD CONSTRAINT FK_TRFT_CLI_TRFT_CLIE_TRFT_SER FOREIGN KEY (CD_SRV)
      REFERENCES TRFT_SERVEURS (CD_SRV)
/


ALTER TABLE TRFT_SERVEUR_FLUX
   ADD CONSTRAINT FK_TRFT_SER_TRFT_SERV_TRFT_FLU FOREIGN KEY (CD_FLUX)
      REFERENCES TRFT_FLUX (CD_FLUX)
/


ALTER TABLE TRFT_SERVEUR_FLUX
   ADD CONSTRAINT FK_TRFT_SER_TRFT_SERV_TRFT_SER FOREIGN KEY (CD_SRV)
      REFERENCES TRFT_SERVEURS (CD_SRV)
/


ALTER TABLE TRFT_TRANSACTION
   ADD CONSTRAINT FK_TRFT_TRA_TRFT_TRAN_TRFT_TRA FOREIGN KEY (CD_TRFT)
      REFERENCES TRFT_TRANSFERT (CD_TRFT)
/



ALTER TABLE TRFT_TRANSFERT
   ADD CONSTRAINT FK_TRFT_TRA_TYPE_DE_T_TRFT_FLU FOREIGN KEY (CD_FLUX)
      REFERENCES TRFT_FLUX (CD_FLUX)
/


